version: '3.1'
services:
  kafka-bench:
    container_name: kafka-bench
    image: bitnami/kafka:latest
    restart: unless-stopped
    networks:
      - default
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_LISTENERS: ${KAFKA_CFG_LISTENERS:-PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094}
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: ${KAFKA_CFG_ADVERTISED_LISTENERS:-PLAINTEXT://kafka-bench:9092,EXTERNAL://127.0.0.1:9094}
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS:-0@kafka-bench:9093}
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER