services:
  kafka-bench-ssl:
    container_name: kafka-bench-ssl
    image: bitnami/kafka:latest
    networks:
      - default
    ports:
      - "9092:9092"
      - "9094:9094"
      - "9095:9095"
    volumes:
      - "./broker-certs/broker_kafka-bench-ssl_server.keystore.jks:/bitnami/kafka/config/certs/kafka.keystore.jks"
      - "./broker-certs/broker_kafka-bench-ssl_server.truststore.jks:/bitnami/kafka/config/certs/kafka.truststore.jks"
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_LISTENERS: ${KAFKA_CFG_LISTENERS:-PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094,EXTERNAL2://:9095}
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:SSL,CONTROLLER:SSL,EXTERNAL:SSL,EXTERNAL2:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: ${KAFKA_CFG_ADVERTISED_LISTENERS:-PLAINTEXT://kafka-bench-ssl:9092,EXTERNAL://localhost:9094,EXTERNAL2://127.0.0.1:9095}
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS:-0@kafka-bench-ssl:9093}
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_SSL_PROTOCOL: TLS
      KAFKA_CFG_SSL_ENABLED_PROTOCOLS: TLSv1.2,TLSv1.1,TLSv1
      KAFKA_CFG_SSL_KEYSTORE_TYPE: JKS
      KAFKA_CFG_SSL_KEYSTORE_LOCATION: /bitnami/kafka/config/certs/kafka.keystore.jks
      KAFKA_CFG_SSL_KEYSTORE_PASSWORD: abcdefgh
      KAFKA_CFG_SSL_KEY_PASSWORD: abcdefgh
      KAFKA_CFG_SSL_TRUSTSTORE_TYPE: JKS
      KAFKA_CFG_SSL_TRUSTSTORE_LOCATION: /bitnami/kafka/config/certs/kafka.truststore.jks
      KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD: abcdefgh
      KAFKA_CFG_SSL_CLIENT_AUTH: required